//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseStudentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        public int Id { get; set; }
        public string BiSt { get; set; }
        public string Predmet { get; set; }
        public string Ocena { get; set; }
    }
}
